# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.12.040232'

RELEASE_GIT_HEAD = '6059d385e084d5aa67c0fd428afd60910ae8f837'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'pantelb/yt-dlp'

ORIGIN = 'pantelb/yt-dlp'

_pkg_version = '2026.01.12.040232'
